### ISSUE TITLE
Please upgrade to 7.6.1

### ISSUE THREAD

**Issue by kikislater** [czka/AUR-grass7#1]
7.6.0 refer to nad2bin which was remove in proj6
No need to replace with sed in files in 7.6.1

Thanks

**Comment by kikislater** [comment]
Working grass here : https://github.com/giscan/AUR-grass

**Comment by czka** [comment]
Done. BTW, @kikislater can you tell if you can install (`g.extension`) and run addons with your https://github.com/giscan/AUR-grass package? Both Python and **C** addons.

**Comment by kikislater** [comment]
Ok thank you @czka 

Yes both addons works : 

> (Mon Jul 22 09:38:08 2019)                                                      
> g.extension extension=v.transects                                               
> Fetching <v.transects> from GRASS GIS Addons repository (be patient)...
> Compiling...
> Installing...
> Updating addons metadata file...
> Installation of <v.transects> successfully finished
> (Mon Jul 22 09:38:15 2019) La commande s'est terminée (7 sec)                   
> (Mon Jul 22 09:42:50 2019)                                                      
> g.extension extension=i.edge                                                    
> Fetching <i.edge> from GRASS GIS Addons repository (be patient)...
> Compiling...
> Installing...
> Updating addons metadata file...
> Installation of <i.edge> successfully finished
> (Mon Jul 22 09:42:57 2019) La commande s'est terminée (6 sec)

**Comment by czka** [comment]
Thanks. Closing this.

**Comment by kikislater** [comment]
But why it's not in AUR ?
