### ISSUE TITLE
nan2bin missing

### ISSUE THREAD

**Issue by cj-sv** [czka/AUR-grass7#2]
Can't build since nad2bin has been removed from the current release of proj. The subject has been open at https://github.com/OSGeo/PROJ/issues/1236

It seems those that need nad2bin should use the proj-datumgrid repo. https://github.com/OSGeo/proj-datumgrid

**Comment by cj-sv** [comment]
nad2bin check has been removed in 7.6.1, we'll just need to update.

https://grass.osgeo.org/news/82/15/GRASS-GIS-7-6-1-released/ configure: nad2bin check no longer needed; (user custom) grids are used via PROJ

**Comment by kikislater** [comment]
Yes but this repo still not work !
