### ISSUE TITLE
conflict between python-termcolors and python2-termcolors

### ISSUE THREAD

**Issue by angelini75** [czka/AUR-grass7#3]
Hi there,

I am sorry if this issue should not be here. I am trying to install grass7 from this repository in Arch Linux.
At first I get this:
```
$ makepkg
==> Making package: grass7 7.6.1-1 (Thu 16 Jan 2020 10:33:57 CET)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> pdal
  -> postgresql
  -> python2-gdal
  -> python2-matplotlib
  -> python2-termcolor
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> doxygen
==> ERROR: Could not resolve all dependencies.
```
So I installed the dependencies, but could not install python2-termcolor**s**
```
looking for conflicting packages...

Packages (2) python-termcolors-0.1.0-2  python2-termcolors-0.1.0-2

```
Should I remove python-termcolors-0.1.0-2? what about the packages that depends on it?
I would appreciate your help.

**Comment by czka** [comment]
@angelini75 Thanks for the report and sorry for my late reply. I don't maintain this PKGBUILD actively anymore. Please use AUR `grass` package instead. It's got to the point of being generally usable. There are some issues after Python 2->3 migration there, but hopefully you can resolve them with the package owner's help.
